SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT=0;
START TRANSACTION;
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


CREATE TABLE IF NOT EXISTS `sagasta_monografias` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `numero` varchar(20) NOT NULL,
  `titulo` varchar(255) NOT NULL DEFAULT 'Sin título',
  `subtitulo` varchar(255) DEFAULT NULL,
  `autor` varchar(255) NOT NULL DEFAULT 'Desconocido',
  `anio` year(4) NOT NULL,
  `categoria` varchar(100) NOT NULL,
  `signatura` varchar(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `signatura` (`signatura`),
  FULLTEXT KEY `titulo` (`titulo`,`subtitulo`,`autor`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
